botsort:
  conf_thres: 0.45
  appearance_thresh: 0.25
  cmc_method: sparseOptFlow
  frame_rate: 30
  match_thresh: 0.8
  new_track_thresh: 0.6
  proximity_thresh: 0.5
  track_buffer: 30
  track_high_thresh: 0.45
