# name of the workflow, what it is doing (optional)
name: CI CPU testing

# events that trigger the workflow (required)
on:
  push:
    branches: [master, CIdebug]
  pull_request:
    # pull request where master is target
    branches: [master]

# the workflow that gets triggerd
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]  # Error: Container action is only supported on Linux
        python-version: [3.9]
        model: ['yolov5n']  # models to test

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50
    steps:
      # Check out the repository recursively, updated to v3
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Prepare environment with python 3.9
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirments
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # If not importing this prior to installing requirements...
          # ImportError: lap requires numpy, please "pip install numpy". Workaround...
          pip install numpy
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
          pip install requests
          python --version
          pip --version
          pip list
        shell: bash
      - name: Tests workflow
        run: |
          # DEEPOCSORT
          python track.py --tracking-method deepocsort --yolo-model ./weights/yolov8n.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          # BOTSORT
          python track.py --tracking-method botsort --yolo-model ./weights/yolov8n.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          # STRONGSORT
          python track.py --tracking-method strongsort --yolo-model ./weights/yolov8n.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          # OCSORT
          python track.py --tracking-method ocsort --yolo-model ./weights/yolov8n.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          # BYTETRACK
          python track.py --tracking-method bytetrack --yolo-model ./weights/yolov8n.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          # EXPORT
          python trackers/reid_export.py --weights ./weights/lmbn_n_cuhk03_d.pt  # export deafults to torchscript
          # STRONGSORT w. EXPORTED REID MODEL
          python track.py --reid-model ./weights/lmbn_n_cuhk03_d.torchscript --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          
          # TRACK WITH SEGMENTATIONS
          python track.py --tracking-method deepocsort --yolo-model ./weights/yolov8n-seg.pt --source ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
          python val.py --tracking-method deepocsort --device cpu --yolo-model yolov8n.pt --benchmark MOT17-mini
          python3 evolve.py --device cpu --objectives HOTA,MOTA,IDF1 --benchmark MOT17-mini --n-trials 1
        shell: bash