# name of the workflow, what it is doing (optional)
name: CI CPU testing

# events that trigger the workflow (required)
on:
  push:
    branches: [master, CIdebug]
  pull_request:
    # pull request where master is target
    branches: [master]

# the workflow that gets triggerd
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]  # Error: Container action is only supported on Linux
        python-version: [3.9]
        model: ['yolov8n']  # models to test

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50
    steps:
      
      - uses: actions/checkout@v3  # Check out the repository
      - uses: actions/setup-python@v4  # Prepare environment with python 3.9
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # If not importing this prior to installing requirements...
          # ImportError: lap requires numpy, please "pip install numpy". Workaround...
          pip install numpy
          # now lap installation goes through
          pip install -e . pytest --extra-index-url https://download.pytorch.org/whl/cpu
          python --version
          pip --version
          pip list
        shell: bash
      - name: Tests all tracking options
        shell: bash  # for Windows compatibility
        env:
          IMG: ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
        run: |
          # deepocsort
          python examples/track.py --tracking-method deepocsort --source $IMG

          # botsort
          python examples/track.py --tracking-method botsort --source $IMG
          
          # strongsort
          python examples/track.py --tracking-method strongsort --source $IMG
          
          # ocsort
          python examples/track.py --tracking-method ocsort --source $IMG
          
          # bytetrack
          python examples/track.py --tracking-method bytetrack --source $IMG
          
      - name: Tests tracker with exported reid model
        env:
            IMG: ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
        shell: bash  # for Windows compatibility
        run: |
          # export
          python boxmot/deep/reid_export.py  # defaults to torchscript
          
          # strongsort w. exported reid model
          python examples/track.py --reid-model examples/weights/mobilenetv2_x1_4_dukemtmcreid.torchscript --source $IMG
      
      - name: Test tracking with seg models
        env:
            IMG: ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
        shell: bash  # for Windows compatibility
        run: |
          # tracking with SEG models
          python examples/track.py --tracking-method deepocsort --yolo-model yolov8n-seg.pt --source $IMG

      - name: Test tracking with pose models
        env:
          IMG: ./assets/MOT17-mini/train/MOT17-05-FRCNN/MOT17-05-FRCNN/000001.jpg
        shell: bash  # for Windows compatibility
        run: |
          # tracking with POSE models
          python3 examples/track.py --yolo-model yolov8n-pose.pt --source $IMG

      - name: Test validation on MOT17 subset
        shell: bash  # for Windows compatibility
        run: |
          # validation on a few MOT17 imges
          python examples/val.py --tracking-method deepocsort --yolo-model yolov8n.pt --benchmark MOT17-mini

      - name: Test evolution on MOT17 subset
        shell: bash  # for Windows compatibility
        run: |
          # evolve a for a single set of parameters
          python examples/evolve.py --objectives HOTA,MOTA,IDF1 --benchmark MOT17-mini --n-trials 1
      
      - name: Pytest tests
        shell: bash  # for Windows compatibility
        run: pytest tests