name: Publish to PyPI

on:
  push:
    branches: [main, create-pip-package]
  workflow_dispatch:
    inputs:
      pypi:
        type: boolean
        description: Publish to PyPI

jobs:
  pypi-upload:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel build twine
          pip install numpy
          pip install -e '.[dev]' --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Create source distribution
        run: |
          python setup.py sdist
      - name: Twine check  # Checks whether the long description will render correctly on PyPI
        run: |
          twine check dist/*
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD --verbose